### PR TITLE
Add missing insights fields

### LINKED ISSUE #11: AdsInsights Object is Missing Fields.
Reference https://developers.facebook.com/docs/marketing-api/reference/ads-insights. The AdInsights Object is missing the estimated_ad_recall_rate and objective fields

### PR DESCRIPTION
**Pull request by xardazz**
Add missing insights fields
Remove lots of insights-related duplicate code
Fixes #11

### CODE REVIEW

**Comment by xardazz** [comment]
@JiamingFB Can you review this one please

**Comment by JiamingFB** [comment]
Hi xardazz,

Thanks a lot for your active contribution to Facebook Ads Java SDK!

As you may have noticed, the classes for ads objects in the SDK share the same structure, and they're generated code based on our Ads API specs. Because we'll have new API version in April, we need to re-generate these classes to make them sync'ed with new API specs. It makes more sense to wait for the new generated code and then apply these fixes. 

For the specific changes in this pull request:
1. Listing accounts by /me/adaccounts: This is super useful and we'd like to include the change right after the new generated SDK is out.
2. Missing insights fields: by regenerating the SDK with API spec in new version, all the new fields  should be included into the SDK (ideally);
3. Insights enums: Duplicated enum values is definitely an issue that we have in the current Java SDK and causes much confusion, and it's actually not specific to insights but also happens in other classes. We have a planned change to better handle enums. More specifically, we'll move all insights related enums into AdsInsights class, Campaign related enums all into Campaign class, and etc. (So that we'll no longer use things like AdAccount.EnumCampaignStatus, but instead use Campaign.EnumStatus.) Because this is a breaking change in programming interface, we'll include this update with the SDK generated with new API version.
4. The Async insights example: Super helpful! Let's include it after the version release.
5. 'mIsRunning' fixes: I just feel this is a little bit fragile. Maybe we should leave the "Job completed" check to application logic, not in the SDK.

Again, thank you so much in helping make the Facebook Ads Java SDK better! I'm really glad to see people interested in the SDK and please let me know if you have any questions.

**Comment by xardazz** [comment]
@JiamingFB Do you know the exact date when it will happen? 
As for the 5. I don't agree. String "Job completed" may change and actually it's SDK purpose to  give  jobComplete check transparently. What I mean is in case of  string changes you can just update SDK without changing anything in code. What do you think?
As for the rest - thanks for the detailed review and reveals on the API future :) As soon as you'll add named changes I'll adjust my code

**Comment by JiamingFB** [comment]
This is resolved in latest code after regenerating the code.

**Pull request closed without merging**
