### PR TITLE
[Java SDK] Handle video encoding failure

### LINKED ISSUE #32: VideoUtils.waitForVideoEncoding does not handle failure correctly
VideoUtils.waitForVideoEncoding will continue retrying even when the call to getVideoStatus indicates that there was an error (it only ever checks if the status is "ready"). It should probably instead return false or throw an exception.

### PR DESCRIPTION
**Pull request by kilink**
If the video_status field indicates encoding failed, throw an Exception.

Fixes #32

### CODE REVIEW

**Comment by cloudxu** [comment]
Thanks, it looks good to me. I'll do some test and update you.

**Comment by cloudxu** [comment]
@kilink, one issue with your diff is that introducing VideoStatus will break many tests and examples. It will become a breaking change. Is it possible you can make it a minimal change without introducing the enum? For breaking changes, we will consider that in the next release version of API.

**Comment by cloudxu** [comment]
ping, @kilink

**Comment by kilink** [comment]
I've updated the branch to use Strings instead of the enum, although I strongly prefer the enum.

What versioning policy does this project use? If it were semver, breaking changes are allowed for any 0.x release.

**Comment by cloudxu** [comment]
@kilink, Thanks. It's mainly because changing string to enum will become a breaking change. Since we codegen most of the code, such breaking change has to be done in our codegen templates. We will look into how we can make them as enum, but probably more from a general way.

**Pull request merged**
